# Generated by Django 4.1.4 on 2023-01-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0003_tf_alter_context_link_alter_tokens_posting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tok",
                        to="context.tokens",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TfIdfList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tf",
        ),
        migrations.RenameModel(
            old_name="context",
            new_name="Contexts",
        ),
        migrations.AddField(
            model_name="tfidflist",
            name="doc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dc",
                to="context.contexts",
            ),
        ),
    ]
