# Generated by Django 4.1.4 on 2023-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0005_rename_contexts_datascraped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datascraped",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="idf",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tfidflist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tokens",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
