# Generated by Django 4.1.4 on 2023-01-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "context",
            "0006_alter_datascraped_id_alter_idf_id_alter_tfidflist_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="datascraped",
            old_name="id",
            new_name="docId",
        ),
        migrations.RenameField(
            model_name="idf",
            old_name="id",
            new_name="idfId",
        ),
        migrations.RenameField(
            model_name="tfidflist",
            old_name="id",
            new_name="tfIdfId",
        ),
        migrations.RenameField(
            model_name="tokens",
            old_name="id",
            new_name="tokId",
        ),
    ]
