# Generated by Django 4.1.4 on 2023-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0009_idf_idf"),
    ]

    operations = [
        migrations.AddField(
            model_name="datascraped",
            name="bodyOrg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datascraped",
            name="titleOrg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfidflist",
            name="lengthFirst",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="tfidflist",
            name="lengthSecond",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="tfidflist",
            name="tfIdfFirstList",
            field=models.JSONField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="tfidflist",
            name="tfIdfSecondList",
            field=models.JSONField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="datascraped",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datascraped",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datascraped",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datascraped",
            name="pubDate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datascraped",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datascraped",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
