# Generated by Django 4.1.4 on 2023-01-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0011_alter_datascraped_category_alter_datascraped_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("docList", models.JSONField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassCrf",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "CrfFirstList",
                    models.JSONField(blank=True, max_length=5000, null=True),
                ),
                (
                    "CrfSecondList",
                    models.JSONField(blank=True, max_length=5000, null=True),
                ),
            ],
        ),
    ]
