# Generated by Django 4.1.4 on 2023-01-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0012_category_classcrf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="ClassCrf",
        ),
    ]
